<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<UseWPF>true</UseWPF>
		<LangVersion>latest</LangVersion>
		<PlatformTarget>x64</PlatformTarget>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
		<Reference Include="System.Windows.Forms" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\Controls\PipeInfo.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="Views\Controls\StructureInfo.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>

</Project>
