<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<UseWPF>true</UseWPF>
		<LangVersion>latest</LangVersion>
		<PlatformTarget>x64</PlatformTarget>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugType>full</DebugType>
		<OutputPath>C:\Users\Nutson\AppData\Roaming\Autodesk\ApplicationPlugins\Civil3DNutsonApp.bundle\Contents\</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
		<OutputPath>bin\$(Configuration)\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="AutoCAD2020.Base" Version="1.0.0" ExcludeAssets="runtime"/>
		<PackageReference Include="Digi-Ants.Civil3D.API.Core" Version="2020.0.0" ExcludeAssets="runtime"/>
		
		<PackageReference Include="Costura.Fody" Version="6.0.0">
				<PrivateAssets>all</PrivateAssets>
				<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<None Include="Resources\dust.png" />
		<None Include="Resources\plumbing.png" />
		<None Include="Resources\pencil-drawing-circles.png" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Extentions\Extentions.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Using Include="Autodesk.AutoCAD.ApplicationServices.Core.Application">
	    <Alias>Application</Alias>
	  </Using>
	  <Using Include="Autodesk.AutoCAD.DatabaseServices.ObjectId">
	    <Alias>ObjectId</Alias>
	  </Using>
	  <Using Include="Extentions" />
	</ItemGroup>
</Project>